#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int motorCount;
	motorCount = 0;
	while (motorCount < 3)
	{
		startMotor(rightMotor, 95);
		wait(2);
		stopMotor(rightMotor);
		wait(2);
		motorCount = motorCount + 1;
	}
}
