#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void LEDControl();
task main()
{
	while (1==1)
	{
		LEDControl();
	}
}
void LEDControl()
{
	if (SensorValue(bumpSwitch)==1)
	{
		turnLEDOn(green);
	}
	else
	{
		turnLEDOff(green);
	}

}
