#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int biggest;
	while (1==1)
	{
		biggest = 0;
		while (SensorValue(bumpSwitch) == 0)
		{
			if (SensorValue(potentiometer)>biggest)
			{
				biggest=SensorValue(potentiometer);
			}
		}
	}
}
